config/routes.rb
Rails.application.routes.draw do
  get 'transactions/index'
  get 'user_companies/index'
  get 'companies/index'
  get 'users/index'

  post 'users/index' => "companies#create"
  post 'companies/index' => "companies#create"
  post 'companies/:id' => "transactions#create"


  root 'users#index'

  resources :companies
  resources :transactions


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :user_companies
    has_many :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :user
    belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :user_companies
  has_many :companies, through: :user_companies
  has_many :transactions
end

app/models/user_company.rb
class UserCompany < ApplicationRecord
    belongs_to :user
    belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all.shuffle
    @quotes = []
    @companies.each do |company|
      @quotes.push(IEX::Resources::Quote.get(company.symbol))
    end
  end

  def create
    symbol = params[:symbol].upcase
    @company = Company.where(symbol: symbol).first
    if @company == nil
      begin
        symbolCheck = IEX::Resources::Company.get(symbol)
      rescue IEX::Errors::SymbolNotFoundError
        flash[:error] = "#{symbol} is not a valid Company"
        redirect_back fallback_location: root_path

      else
        @company = Company.new(symbol:symbol)
        if @company.save
          flash[:success] = "Added #{symbol} to Companies"
          if params[:page] == "portfolio"
            redirect_to @company
          else
            redirect_to companies_path
          end
        else
          flash[:error] = "Error adding Company"
        end
      end
    else
      if params[:page] == "portfolio"
        redirect_to @company
      else
        redirect_to companies_path
        flash[:success] = "Company is already on List"
      end
    end
  end
  

  def show
    @company = Company.find(params[:id])
    @companyInfo = IEX::Resources::Company.get(@company.symbol)
    @shares = num_shares(@company)
    @avg = avg_price(@company)
    @price = IEX::Resources::Price.get(@company.symbol)

    @transactions = Transaction.where(user_id:current_user.id, company_id:@company.id)

  end

  def num_shares(company)
    transactions = Transaction.where(user_id:current_user.id,company_id:company.id)
    counter = 0
    transactions.each do |transaction|
      if transaction.buy
        counter = counter + transaction.shares
      else
        counter = counter - transaction.shares
      end
    end
    return counter
  end

  def avg_price(company)
    transactions = Transaction.where(user_id:current_user.id,company_id:company.id, buy:true)
    numerator = 0
    denominator = 0
    transactions.each do |transaction|
      numerator = numerator + (transaction.shares*transaction.price)
      denominator = denominator + transaction.shares
    end
    if denominator != 0
      return (numerator/denominator).round(3)
    else
      return '-'
    end
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.where(user_id:current_user.id)
  end

  def create
    @company = Company.find(params[:company_id].to_i)
    name = IEX::Resources::Company.get(@company.symbol).company_name
      if params[:buy] == "true"
          cashValue = (current_user.cash.to_f - (params[:price].to_f*params[:shares].to_f)).round(3)
          if cashValue > 0
              @transaction = Transaction.new(user_id:current_user.id,company_id:params[:company_id], price:params[:price],shares:params[:shares],buy:params[:buy])
              if @transaction.save
                  current_user.update(cash:cashValue)
                  if UserCompany.where(user_id: current_user.id, company_id:params[:company_id].to_i).empty?
                      UserCompany.create(user_id: current_user.id, company_id:params[:company_id].to_i)
                  end
                  flash[:success] = "Successfully purchased #{params[:shares]} shares of #{name}"
                  redirect_to @company
              else
                  flash[:error] = "There was an Error with your purchase. Please Try Again."
                  redirect_to @company
              end
          else
              flash[:error] = "You don't have enough money to complete this purchase"
              redirect_to @company
          end
      else
          puts "43"
          cashValue = (current_user.cash.to_f + (params[:price].to_f*params[:shares].to_f)).round(3)
          puts "44"
          if params[:totalShares].to_i >= params[:shares].to_i 
              @transaction = Transaction.new(user_id:current_user.id,company_id:params[:company_id], price:params[:price],shares:params[:shares],buy:params[:buy])
              if @transaction.save
                  puts "saving"
                  current_user.update(cash:cashValue)
                  flash[:success] = "Successfully sold #{params[:shares]} shares of #{name}"
                redirect_to @company
              else
                  puts "error"
                  flash[:error] = "There was an Error with your purchase. Please Try Again."
                  redirect_to @company
              end
          else
              puts "no money"
              flash[:error] = "You don't have enough shares to sell"
              redirect_to @company
          end
      end
  end
end

app/controllers/user_companies_controller.rb
class UserCompaniesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login

  def index
    @value = stockPortfolioValue + current_user.cash
    @initialDeposit = current_user.initial_deposit
    @change = (((@value/@initialDeposit)*100)-100).round(2)
    @cash = current_user.cash

    @quotes = []
    @avg = []
    @shares = []

    @companies = current_user.companies
    @companies.each do |company|
      @quotes.push(IEX::Resources::Quote.get(company.symbol))
      @avg.push(avg_price(company))
      @shares.push(num_shares(company))
    end
  end

  def num_shares(company)
    transactions = Transaction.where(user_id:current_user.id,company_id:company.id)
    counter = 0
    transactions.each do |transaction|
      if transaction.buy
        counter = counter + transaction.shares
      else
        counter = counter - transaction.shares
      end
    end
    return counter
  end

  def avg_price(company)
    transactions = Transaction.where(user_id:current_user.id,company_id:company.id, buy:true)
    numerator = 0
    denominator = 0
    transactions.each do |transaction|
      numerator = numerator + (transaction.shares*transaction.price)
      denominator = denominator + transaction.shares
    end
    if denominator != 0
      return (numerator/denominator).round(3)
    else
      return '-'
    end
  end

  def stockPortfolioValue
    counter = 0
    current_user.companies.each do |company|
      currentPrice = IEX::Resources::Price.get(company.symbol)
      counter = counter + (num_shares(company)*currentPrice)
    end

    return counter 
  end


  def splash
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def bootstrap_class_for flash_type
      { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
    end
  
    def flash_messages(opts = {})
      flash.each do |msg_type, message|
        concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do 
                concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
                concat message 
              end)
      end
      nil
    end
  end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/user_companies_helper.rb
module UserCompaniesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/index.html.erb
<div class="container">
    <br><h1 class="text-center">Company List</h1>
    <div class="row">
        <table class="table table-striped table-dark rounded-bottom">
        <thead>
            <tr>
            <th scope="col">Symbol</th>
            <th scope="col">Company Name</th>
            <th scope="col">Industry</th>
            <th scope="col">Low</th>
            <th scope="col">High</th>
            <th scope="col">% Change</th>
            <th scope="col">Current Price</th>

            </tr>
        </thead>
        <tbody>
            <%@quotes.each do |quote|%>
                <tr>
                <th scope="row"><%=link_to "#{quote.symbol}", "/companies/#{Company.where(symbol:quote.symbol).first.id}", class:"link"%></th>
                <td><%=quote.company_name%></td>
                <td><%=IEX::Resources::Company.get(quote.symbol).industry%></td>
                <td><%="$#{quote.high}"%></td>
                <td><%="$#{quote.low}"%></td>
                <%if quote.change > 0%>
                    <td class="green"><%=quote.change_percent_s%></td>
                <%else%>
                    <td class="red"><%=quote.change_percent_s%></td>
                <%end%>
                <td><%="$#{quote.latest_price}"%></td>
                </tr>
            <%end%>
        </tbody>
        </table>
    </div><br><br><br>

    <div class="row footerSpace">
        <div class="col ">
            <%= form_with(model:@company, local:true,class:"justify-content-center form-inline") do |f| %>
                <div class="form-group mx-sm-3 mb-2">
                    <%=f.label :symbol, "Add Company by Symbol:",class:"padding"%>
                    <%= f.text_field :symbol,placeholder:"ex. AAPL", class:"form-control",style:"text-transform:uppercase" %>
                    <%= f.hidden_field :page, value: "list" %>
                </div>
                <%= f.submit "Submit",class:"btn btn-primary mb-2 "%>
            <% end %>
        </div>
    </div>

</div>

app/views/companies/show.html.erb
<div class="container">
    <h1 class=" text-center"><strong>Company Information</strong></h1>
<div class="jumbotron">
    <dl class="row">
        <dt class="col-2">Symbol:</dt><br>
        <dd class="col-10"><%=@company.symbol%></dd>

        <dt class="col-2">Name:</dt>
        <dd class="col-10"><%=@companyInfo.company_name%></dd>

        <dt class="col-2">Exchange:</dt>
        <dd class="col-10"><%=@companyInfo.exchange%></dd>

        <dt class="col-2">Industry:</dt>
        <dd class="col-10"><%=@companyInfo.industry%></dd>

        <dt class="col-2">Description:</dt>
        <dd class="col-10"><%=@companyInfo.description%></dd>

        <dt class="col-2">CEO:</dt>
        <dd class="col-10"><%=@companyInfo.ceo%></dd>

        <dt class="col-2">Sector:</dt>
        <dd class="col-10"><%=@companyInfo.sector%></dd>

        <dt class="col-2">Website:</dt>
        <dd class="col-10"><a href="<%=@companyInfo.website%>"><%=@companyInfo.website%></a></dd>
    </dl>
</div>
        <div class="card-group topspace text-center mx-auto" style="width: 40rem;">
                <div class="card card-sharp">
                    <div class="card-header"><strong>Number of Shares:</strong></div>
                    <p class="card-text cashText"><%=@shares%></p>
                </div>
                <div class="card card-sharp">
                    <div class="card-header"><strong>Avg. Price Paid:</strong></div>
                    <p class="card-text cashText"><%="$#{@avg}"%></p>
                </div>
                <div class="card card-sharp">
                    <div class="card-header"><strong>Current Price:</strong></div>
                    <p class="card-text cashText"><%="$#{@price}"%></p>
                </div>
        </div>
        <div class='wrapper text-center'>
            <div class="btn-group" role="group">
                    <button type="button" class="btn btn-success btn-lg btn-sharp" style="width: 20.04rem;" data-toggle="modal" data-target="#buyModal"><i class="fa fa-plus"></i> Buy Stock</button>
                    <button type="button" class="btn btn-danger btn-lg btn-sharp" style="width: 20.04rem;" data-toggle="modal" data-target="#sellModal"><i class="fa fa-minus"></i> Sell Stock</button>
            </div>
        </div>


            
        <div class="modal fade" id="buyModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Buy Shares of <%=@companyInfo.company_name%></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                    <div class="modal-body">
                        <h6 class="text-center"><strong>Current Price: $<%=@price%></strong></h4><br>
                        <h6 class="text-center"><strong>Available Funds:$<%=current_user.cash%></strong></h4><br>

                        <%= form_with(model:@transaction, local:true) do |f| %>
                                <%=f.label :shares, "Number of Shares:"%>
                                <%= f.text_field :shares, placeholder:"min. 1",class:"form-control"%>
                                <%= f.hidden_field :company_id, value: @company.id %>
                                <%= f.hidden_field :buy, value: true %>
                                <%= f.hidden_field :price, value: @price %>
                                <%= f.hidden_field :totalShares, value: @shares %>
                                <br><%= f.submit "Submit",class:"btn btn-primary mb-2 "%>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>    

        <div class="modal fade" id="sellModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Sell Shares of <%=@companyInfo.company_name%></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                    <div class="modal-body">
                        <h6 class="text-center"><strong>Current Price: $<%=@price%></strong></h4><br>
                        <%= form_with(model:@transaction, local:true) do |f| %>
                                <%=f.label :shares, "Number of Shares:"%>
                                <%= f.text_field :shares, placeholder:"max. #{@shares}",class:"form-control"%>
                                <%= f.hidden_field :company_id, value: @company.id %>
                                <%= f.hidden_field :buy, value: false %>
                                <%= f.hidden_field :price, value: @price %>
                                <%= f.hidden_field :totalShares, value: @shares %>
                                <br><%= f.submit "Submit",class:"btn btn-primary mb-2 "%>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>  


    <h2 class="text-center">Transaction History</h2>

    <div class="row top">
        <table class="bottom table table-striped table-dark rounded-bottom">
        <thead>
            <tr>
            <th scope="col">Date/Time</th>
            <th scope="col">Transaction Type</th>
            <th scope="col"># of Shares</th>
            <th scope="col">Price per Share</th>
            </tr>
        </thead>
        <tbody>
            <%if !@transactions.empty?%>
                <%@transactions.reverse.each do |transaction|%>
                    <tr>
                    <th scope="row"><%=transaction.created_at.strftime("%d %b %Y") %></th>
                    <% if transaction.buy == true %>
                        <td class="green">Buy</th>
                    <% else %>
                        <td class="red">Sell</th>
                    <%end%>

                    <td><%=transaction.shares%></td>
                    <td><%=transaction.price%></td>
                    </tr>
                <%end%>
            <%else%>
                    <tr>
                    <th scope="row">-</th>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    </tr>
            <%end%>
        </tbody>
        </table>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FauxTrader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">
      <%=image_tag ("logo.png"), class:"d-inline-block align-top"%>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav mr-auto">
        <% if signed_in? %>
          <%= link_to "My Portfolio", root_path, class: "nav-item nav-link" %>
          <%= link_to "Companies", companies_path, class: "nav-item nav-link" %>
          <%= link_to "All Transactions", transactions_path, class: "nav-item nav-link" %>

        <% else %>
          <%= link_to 'Sign in', sign_in_path, class: "nav-item nav-link" %>
          <%= link_to 'Sign Up', sign_up_path, class: "nav-item nav-link" %>
        <% end %>
      </div>
      <% if signed_in? %>
        <div class="navbar-nav">
            <%= link_to 'Sign out', sign_out_path, method: :delete,class: "nav-item nav-link my-2 my-lg-0" %>
        </div>
      <%end%>
    </div>
  </nav>


    <%= flash_messages %>
    <%= yield %>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">&copy; 2018 FauxTrader.com</span>
      </div>
    </footer>
  </body>
</html>

app/views/transactions/index.html.erb
<div class="container">
    <h1 class="text-center">All Transactions</h1>
    <table class="bottom table table-striped table-dark rounded-bottom">
        <thead>
            <tr>
            <th scope="col">Date/Time</th>
            <th scope="col">Symbol</th>
            <th scope="col">Company Name</th>
            <th scope="col">Transaction Type</th>
            <th scope="col"># of Shares</th>
            <th scope="col">Price per Share</th>
            </tr>
        </thead>
        <tbody>
            <%if !@transactions.empty?%>
                <%@transactions.each do |transaction|%>
                    <tr>
                    <th scope="row"><%="#{transaction.created_at.strftime("%d %b %Y")}"%></th>
                    <th scope="row"><%=link_to "#{transaction.company.symbol}", "/companies/#{transaction.company.id}", class:"link"%></th>
                    <td><%=IEX::Resources::Company.get(transaction.company.symbol).company_name%></th>
                    <% if transaction.buy == true %>
                        <td class="green">Buy</th>
                    <% else %>
                        <td class="red">Sell</th>
                    <%end%>

                    <td><%=transaction.shares%></td>
                    <td><%=transaction.price%></td>
                    </tr>
                <%end%>
            <%else%>
                    <tr>
                    <th scope="row">-</th>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    </tr>
            <%end%>
        </tbody>
        </table>
</div>

app/views/user_companies/index.html.erb
<h1>UserCompanies#index</h1>
<p>Find me in app/views/user_companies/index.html.erb</p>

app/views/users/_form.html.erb
<center> 
<div class="text-field">
 <!-- <%= form.label :email %> -->
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
 <!-- <%= form.label :password %> -->
  <%= form.password_field :password %>
</div>
</center>

app/views/users/index.html.erb
<div class="container">
<br><h1 class="text-center">My Portfolio</h1>
    <div class="row topspace text-center">
        <div class="col-4">
            <div class="card mx-auto leftCard" style="width: 20rem;">
                <div class="card-header"><strong>Initial Deposit:</strong></div>
                <p class="card-text cashText"><%="$#{@initialDeposit.round(0)}"%></p>
            </div>
        </div>

        <div class="col-4">
            <div class="card mx-auto" style="width: 20rem;">
                <div class="card-header"><strong>Current Portfolio Value:</strong></div>
                <p class="card-text cashText" ><%="$#{@value.round(2)}"%></p>
            </div>
        </div>

        <div class="col-4">
            <div class="card mx-auto rightCard" style="width: 20rem;">
                <div class="card-header"><strong>Difference:</strong></div>
                <%if @change < 0%>
                    <p class="card-text cashText red" ><%="#{@change}%"%></p>
                <%else%>
                    <p class="card-text cashText green" ><%="+#{@change}%"%></p>
                <%end%>
            </div>
        </div>
    </div><br>
    <div class="row rounded">
        <table class="table table-striped table-dark rounded-bottom">
        <thead>
            <tr>
            <th scope="col">Symbol</th>
            <th scope="col">Company Name</th>
            <th scope="col"># of Shares</th>
            <th scope="col">Low</th>
            <th scope="col">High</th>
            <th scope="col">% Change</th>
            <th scope="col">Avg. Price Paid</th>
            <th scope="col">Current Price</th>

            </tr>
        </thead>
        <tbody>
        <%if @quotes.size != 0%>
            <%@quotes.size.times do |index|%>
                <tr>
                <th scope="row"><%=link_to "#{@quotes[index].symbol}", "/companies/#{@companies[index].id}", class:"link"%></th>
                <td><%=@quotes[index].company_name%></td>
                <td><%=@shares[index]%></td>
                <td><%="$#{@quotes[index].high}"%></td>
                <td><%="$#{@quotes[index].low}"%></td>
                <%if @quotes[index].change > 0%>
                    <td class="green"><%=@quotes[index].change_percent_s%></td>
                <%else%>
                    <td class="red"><%=@quotes[index].change_percent_s%></td>
                <%end%>
                <%if @avg[index] != "-"%>
                    <td><%="$#{@avg[index]}"%></td>
                <%else%>
                    <td><%="#{@avg[index]}"%></td>
                <%end%>
        
                <td><%="$#{@quotes[index].latest_price}"%></td>
                </tr>
            <%end%>
        <%else%>
            <tr>
            <th scope="row">-</th>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            </tr>
        <%end%>

        </tbody>
        </table>
    </div><br><br><br>
    <h2 class="text-center">Find Companies</h2><br><br>
    <div class="row text-center">
        <div class="col ">
            <div class="card mx-auto rightCard" style="width: 18rem;">
                <div class="card-header"><strong>Available to Spend:</strong></div>
                <p class="card-text cashText" ><%="$#{@cash}"%></p>
            </div>
        </div>
    </div>

    <div class="row footerSpace">
        <div class="col ">
            <%= form_with(model:@company, local:true,class:"justify-content-center form-inline") do |f| %>
                <div class="form-group mx-sm-3 mb-2">
                    <%=f.label :symbol, "Search by Company Symbol:",class:"padding"%>
                    <%= f.text_field :symbol,placeholder:"ex. AAPL", class:"form-control",style:"text-transform:uppercase" %>
                    <%= f.hidden_field :page, value: "portfolio" %>
                </div>
                <%= f.submit "Submit",class:"btn btn-primary mb-2 "%>
            <% end %>
        </div>
    </div>

</div>

app/views/users/new.html.erb
<div class="container">
  <div id="clearance" class="sign-up">
    <h2><%= t(".title") %></h2>
    <%= bootstrap_form_for @user do |form| %>
      <%= render partial: '/users/form', object: form %>

      <div class="submit-field">
        <%= form.submit %>
      </div>

      <div class="other-links">
        <%= link_to t(".sign_in"), sign_in_path %>
      </div>
    <% end %>
  </div>
</div>